${ARBITRATION}/rtl/majority3.v
${MISC}/rtl/dsync.v
${STORAGE}/rtl/fifo.v
${STORAGE}/rtl/fifo_fwft.v
${UART}/rtl/uart_rx.v
${UART}/rtl/uart_rx_fifo.v
${UART}/rtl/uart_tx.v
${UART}/rtl/uart_tx_fifo.v
${UART}/rtl/uart.v
${UART}/test/testbench/uart_loopback_parity.sv
